### ISSUE TITLE
KeyError: 'imageset'

### ISSUE THREAD

**Issue by FabricioProjects** [Abhijit-2592/Keras_object_detection#2]
Hello again @Abhijit-2592 
Now Im trying a 1 class custom dataset in a .txt file like this:
/home/fabricio/notebooks/fcnn/tpn/image/195.jpg,52,462,938,560,text
/home/fabricio/notebooks/fcnn/tpn/image/196.jpg,1200,777,2143,914,text
/home/fabricio/notebooks/fcnn/tpn/image/196.jpg,2205,755,2561,895,text
...

Im getting an error (title of this issue) in these lines on train file:
train_imgs = [s for s in all_imgs if s['imageset'] == 'train']
val_imgs = [s for s in all_imgs if s['imageset'] == 'valid']

How your code is suppose to manage the train and validation besides the 'train_path' argument?
the 'imageset' is obviously not defined nowhere

**Comment by FabricioProjects** [comment]
I understood the problem. The filename must have '/train/' or '/valid/' so the code can split the training and validation images like below:

/home/fabricio/notebooks/fcnn/datasets/image_split/train/300.jpg,1107,217,1404,307,text
/home/fabricio/notebooks/fcnn/datasets/image_split/valid/301.jpg,1445,800,1909,1036,text

**Comment by Abhijit-2592** [comment]
yes, you are right @FabricioProjects. I made it so that the training set and the validation sets are split before hand. I need reviews whether to keep it this way or randomly split with a validation %
