### ISSUE TITLE
RPN Stride

### ISSUE THREAD

**Issue by deepaklunked** [Abhijit-2592/Keras_object_detection#6]
What would be the RPN stride for other architectures like inceptionv3, resnet50? For vgg16 its 16.
Also, any plans on including new networks like Xception, etc?

**Comment by Abhijit-2592** [comment]
The RPN stride for inceptionv3 n resnet50 as given in this repo is 16. And you can easily implement any other architecture. Just follow the docs

**Comment by deepaklunked** [comment]
Does it not change based on the network. It's basically the ratio to which the image is shrunk to get the feature map right? Please correct me if I am wrong..

**Comment by Abhijit-2592** [comment]
You are right it changes depending on the architecture. The RPN layer in Faster-RCNN architecture can be inserted anywhere in between the CNN architectures. For example in VGG-16 the authors inserted the RPN layer after "block_5_conv3" (keras name) layer, which has an effective stride of 16. Similarly you can insert it anywhere in the (VGG-16) architecture and change the RPN stride accordingly (Say block4_conv3 and set RPN stride = 8). In case of Inception-v3 I have inserted the RPN layer after "mixed-7" (keras name) layer which has an effective RPN stride of 16 pixels. Similarly for Resnet-50. All the architectures in this repo has rpn_stride = 16

You can interpret it like : The layers before the RPN are positional invariant/ insensitive and layers after the RPN are positional sensitive/variant. Thus you can define your own CNN architecture and insert the RPN layer in between any layer and specify the rpn stride accordingly. Refer the [link](https://github.com/Abhijit-2592/Keras_object_detection/blob/73883fc2078cd3c9c7e3337c3a404114fd38e706/Faster_RCNN_API/keras_frcnn/nn_arch_vgg16.py#L15) for steps to implement new architectures. (You can copy paste the RPN layer code for any architecture but, you must implement the nn_base() and classifier() methods for different architectures.)

**Caution** : Determining at which layer to insert the RPN is a study in itself (A lower RPN stride does not always guarantee a better detection). You can refer [this](https://arxiv.org/pdf/1611.10012.pdf) paper from google for a few more famous  architectures and their rpn stride.

**PS**: In the paper they have used the Tensorflow naming terminology to specify the layer names. You must look into the source code to determine the layer name in keras

**Comment by deepaklunked** [comment]
Thanks. That was really helpful..
