### ISSUE TITLE
Anchor size for detecting small objects

### ISSUE THREAD

**Issue by ant1pink** [Abhijit-2592/Keras_object_detection#8]
Continue to [this problem](https://github.com/Abhijit-2592/Keras_object_detection/issues/5). I had the same problem here, the min side of the images in my datasets is much larger than 600. If I resize the min side to 600, the logo (ROI) that I am going to detect is becoming even smaller.  As the result, the smallest anchor-size from the default setting would be too big for it. So as you suggested, I have changed im_size to 1000 and anchor-size to 32, and I got a better result. But I am not sure how to set num_rois, is it the more the better for my case?

**Comment by ant1pink** [comment]
According to [this blog](https://blog.deepsense.ai/region-of-interest-pooling-explained/), I think the number of ROI should be the more the better, especially for those cases that final classification loss is increasing. It is because that if an object is not detected during the region proposal, there’s no way to correctly classify it in the final classification.

**Comment by Abhijit-2592** [comment]
guess you solved the problem
